/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ['class'],
  content: [
    './pages/**/*.{ts,tsx}',
    './components/**/*.{ts,tsx}',
    './app/**/*.{ts,tsx}',
    './src/**/*.{ts,tsx}',
  ],
  prefix: '',
  theme: {
    container: {
      center: true,
      padding: '2rem',
      screens: {
        '2xl': '1400px',
      },
    },
    extend: {
      colors: {
        // Map CSS variables to Tailwind color scales
        primary: {
          50: 'var(--primary-50)',
          100: 'var(--primary-100)',
          200: 'var(--primary-200)',
          300: 'var(--primary-300)',
          400: 'var(--primary-400)',
          500: 'var(--primary-500)',
          600: 'var(--primary-600)',
          700: 'var(--primary-700)',
          800: 'var(--primary-800)',
          900: 'var(--primary-900)',
          950: 'var(--primary-950)',
          DEFAULT: 'var(--primary)',
          foreground: 'var(--primary-foreground)',
        },
        secondary: {
          50: 'var(--secondary-50)',
          100: 'var(--secondary-100)',
          200: 'var(--secondary-200)',
          300: 'var(--secondary-300)',
          400: 'var(--secondary-400)',
          500: 'var(--secondary-500)',
          600: 'var(--secondary-600)',
          700: 'var(--secondary-700)',
          800: 'var(--secondary-800)',
          900: 'var(--secondary-900)',
          950: 'var(--secondary-950)',
          DEFAULT: 'var(--secondary)',
          foreground: 'var(--secondary-foreground)',
        },
        accent: {
          50: 'var(--accent-50)',
          100: 'var(--accent-100)',
          200: 'var(--accent-200)',
          300: 'var(--accent-300)',
          400: 'var(--accent-400)',
          500: 'var(--accent-500)',
          600: 'var(--accent-600)',
          700: 'var(--accent-700)',
          800: 'var(--accent-800)',
          900: 'var(--accent-900)',
          950: 'var(--accent-950)',
          DEFAULT: 'var(--accent)',
          foreground: 'var(--accent-foreground)',
        },
        plum: {
          50: 'var(--plum-50)',
          100: 'var(--plum-100)',
          200: 'var(--plum-200)',
          300: 'var(--plum-300)',
          400: 'var(--plum-400)',
          500: 'var(--plum-500)',
          600: 'var(--plum-600)',
          700: 'var(--plum-700)',
          800: 'var(--plum-800)',
          900: 'var(--plum-900)',
          950: 'var(--plum-950)',
          DEFAULT: 'var(--plum)',
        },
        sage: {
          50: 'var(--sage-50)',
          100: 'var(--sage-100)',
          200: 'var(--sage-200)',
          300: 'var(--sage-300)',
          400: 'var(--sage-400)',
          500: 'var(--sage-500)',
          600: 'var(--sage-600)',
          700: 'var(--sage-700)',
          800: 'var(--sage-800)',
          900: 'var(--sage-900)',
          950: 'var(--sage-950)',
          DEFAULT: 'var(--sage)',
        },
        rust: {
          50: 'var(--rust-50)',
          100: 'var(--rust-100)',
          200: 'var(--rust-200)',
          300: 'var(--rust-300)',
          400: 'var(--rust-400)',
          500: 'var(--rust-500)',
          600: 'var(--rust-600)',
          700: 'var(--rust-700)',
          800: 'var(--rust-800)',
          900: 'var(--rust-900)',
          950: 'var(--rust-950)',
          DEFAULT: 'var(--rust)',
        },
        taupe: {
          50: 'var(--taupe-50)',
          100: 'var(--taupe-100)',
          200: 'var(--taupe-200)',
          300: 'var(--taupe-300)',
          400: 'var(--taupe-400)',
          500: 'var(--taupe-500)',
          600: 'var(--taupe-600)',
          700: 'var(--taupe-700)',
          800: 'var(--taupe-800)',
          900: 'var(--taupe-900)',
          950: 'var(--taupe-950)',
          DEFAULT: 'var(--taupe)',
        },
        cream: {
          50: 'var(--cream-50)',
          100: 'var(--cream-100)',
          200: 'var(--cream-200)',
          300: 'var(--cream-300)',
          400: 'var(--cream-400)',
          500: 'var(--cream-500)',
          600: 'var(--cream-600)',
          700: 'var(--cream-700)',
          800: 'var(--cream-800)',
          900: 'var(--cream-900)',
          950: 'var(--cream-950)',
          DEFAULT: 'var(--cream)',
        },
        inky: {
          50: 'var(--inky-50)',
          100: 'var(--inky-100)',
          200: 'var(--inky-200)',
          300: 'var(--inky-300)',
          400: 'var(--inky-400)',
          500: 'var(--inky-500)',
          600: 'var(--inky-600)',
          700: 'var(--inky-700)',
          800: 'var(--inky-800)',
          900: 'var(--inky-900)',
          950: 'var(--inky-950)',
          DEFAULT: 'var(--inky)',
        },
        // Standard shadcn/ui colors
        background: 'var(--background)',
        foreground: 'var(--foreground)',
        card: {
          DEFAULT: 'var(--card)',
          foreground: 'var(--card-foreground)',
        },
        popover: {
          DEFAULT: 'var(--popover)',
          foreground: 'var(--popover-foreground)',
        },
        muted: {
          DEFAULT: 'var(--muted)',
          foreground: 'var(--muted-foreground)',
        },
        destructive: {
          DEFAULT: 'var(--destructive)',
          foreground: 'hsl(var(--destructive-foreground))',
        },
        border: 'var(--border)',
        input: 'var(--input)',
        ring: 'var(--ring)',
        chart: {
          1: 'var(--chart-1)',
          2: 'var(--chart-2)',
          3: 'var(--chart-3)',
          4: 'var(--chart-4)',
          5: 'var(--chart-5)',
        },
        sidebar: {
          DEFAULT: 'var(--sidebar)',
          foreground: 'var(--sidebar-foreground)',
          primary: 'var(--sidebar-primary)',
          'primary-foreground': 'var(--sidebar-primary-foreground)',
          accent: 'var(--sidebar-accent)',
          'accent-foreground': 'var(--sidebar-accent-foreground)',
          border: 'var(--sidebar-border)',
          ring: 'var(--sidebar-ring)',
        },
      },
      borderRadius: {
        lg: 'var(--radius-lg)',
        md: 'var(--radius-md)',
        sm: 'var(--radius-sm)',
        xl: 'var(--radius-xl)',
      },
      keyframes: {
        'accordion-down': {
          from: { height: '0' },
          to: { height: 'var(--radix-accordion-content-height)' },
        },
        'accordion-up': {
          from: { height: 'var(--radix-accordion-content-height)' },
          to: { height: '0' },
        },
      },
      animation: {
        'accordion-down': 'accordion-down 0.2s ease-out',
        'accordion-up': 'accordion-up 0.2s ease-out',
      },
    },
  },
  plugins: [require('tailwindcss-animate')],
}
